name: IDS Split DS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3', '8.4']
    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: ${{ matrix.dependency-versions }}
      - name: "Setup tests"
        run: |
          make test-setup
      - name: "Run tests"
        run: |
          make test
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage-cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Coverage results to summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - name: Code Coverage Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: phpunit-coverage-${{ matrix.php-versions }}
          path: ./coverage-html


  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3', '8.4']
    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
      - name: "Run PHPStan"
        run: |
          ./vendor/bin/phpstan analyse --no-progress
